id: DAFDB1DDF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-07T09:22:35+00:00'
last_modified: '2022-05-30T06:48:05.785693+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    90a6:
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      order: 47
      base_file: 90a6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
